extends: default

rules:
  document-start: disable

  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  line-length:
    max: 250
    level: warning

  truthy: disable

  new-line-at-end-of-file:
    level: warning
