extends: default

rules:
  document-start: disable

  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  line-length:
    max: 250
    level: warning

  truthy: disable

  new-line-at-end-of-file:
    level: warning
