- alias: "Bathroom Motion – Auto Lights"
  id: bathroom_motion_auto_lights
  mode: restart # Important so the timer resets as long as motion continues

  trigger:
    # Motion detected
    - platform: state
      entity_id: binary_sensor.downstairs_bath_motion
      to: "on"

    # Motion cleared (idle)
    - platform: state
      entity_id: binary_sensor.downstairs_bath_motion
      to: "off"
      for: "00:02:00" # wait 2 minutes after no motion before turning off

  action:
    - choose:
        # When motion is detected → turn on lights
        - conditions:
            - condition: state
              entity_id: binary_sensor.downstairs_bath_motion
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.downstairs_bathroom

        # When motion stops for X minutes → turn off lights
        - conditions:
            - condition: state
              entity_id: binary_sensor.downstairs_bath_motion
              state: "off"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.downstairs_bathroom
